#  relay-js CI

image: node:14.15.4

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - cd packages/sdk
              - npm install
              - npm run build
              - npm test
        - step:
            name: Code linting
            script:
              - cd packages/sdk
              - npm install eslint
              - npx eslint .
            caches:
              - node
